apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ibm-integration-operatorgroup
  namespace: ipt
  labels:
    backup.integration.ibm.com/component: operatorgroup        
spec:
  targetNamespaces:
  - ipt