apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-integration-platform-navigator
  namespace: ipt
  labels:
    backup.integration.ibm.com/component: subscription  
  annotations:
    argocd.argoproj.io/sync-wave: "2"      
spec:
  channel: v7.3-sc2
  installPlanApproval: Automatic
  name: ibm-integration-platform-navigator
  source: ibm-integration-platform-navigator-catalog
  sourceNamespace: openshift-marketplace